//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestionInventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GestionInventario()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int IdGestionInventario { get; set; }
        public int IdUsuario { get; set; }
        public string TipoGestion { get; set; }
        public int IdTipMovimiento { get; set; }
        public Nullable<int> CantidadProductoGestionado { get; set; }
        public int UsuarioGestion { get; set; }
        public System.DateTime FechaGestion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual TipoMovimiento TipoMovimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
