//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(InventarioMetadada)]
    
    public partial class GestionInventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GestionInventario()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int IdGestionInventario { get; set; }
        public int IdUsuario { get; set; }
        public string TipoGestion { get; set; }
        public int IdTipMovimiento { get; set; }
        public Nullable<int> CantidadProductoGestionado { get; set; }
        public int UsuarioGestion { get; set; }
        public System.DateTime FechaGestion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual TipoMovimiento TipoMovimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
