//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ProveedorMetadata))]

    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int IdProveedor { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe brindar un nombre")]
        public string Nombre_Proveedor { get; set; }
        public string Dsc_Proveedor { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe brindar un nombre de contacto")]
        public string Nombre_Contacto { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe brindar un número telefónico")]
        [StringLength(13, MinimumLength = 12, ErrorMessage = "El formato válido es +506 88888888")]
        [DataType (DataType.PhoneNumber)]
        public string Telefono { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe brindar un correo")]
        [DataType(DataType.EmailAddress)]
        public string Correo { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe Seleccionar un País")]
        public string Pais { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe brindar una dirección")]
        [StringLength(120, MinimumLength = 12, ErrorMessage = "La dirección es muy breve, brinde más detalles")]
        [DataType(DataType.MultilineText)]
        public string Direccion { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "No se ha asignado un estado.")]
        public Nullable<byte> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
