//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(UsuarioMetadata))]

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.GestionInventario = new HashSet<GestionInventario>();
        }
    
        public int IdUsuario { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe brindar un número de identificación")]
        [StringLength(9, MinimumLength = 4, ErrorMessage = "El formato no es válido")]
        public string NumeroIdentificacion { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe proporcionar un nombre")]
        public string Nombre { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe proporcionar el primer apellido")]
        public string PrimerApellido { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe proporcionar el segundo apellido")]
        public string SegundoApellido { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe seleccionar un tipo de rol")]
        public int IdRol { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe brindar un correo")]
        [DataType(DataType.EmailAddress)]
        public string Correo { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe brindar una palabra secreta")]
        public string Clave { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "No se ha asignado un estado.")]
        public Nullable<byte> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GestionInventario> GestionInventario { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
